### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by shtirlits-bsa20** [LH346/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by shtirlits-bsa20** [comment]
Основатель национал-социализма, рейхсканцлер, диктатор Третьего рейха, фюрер НСДАП и Германии. Является человеком, развязавшим Вторую мировую войну.

**Comment by LH346** [comment]
От души
